enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[pixiv]
apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/pixiv/"
uptodown-dlurl = "https://pixiv.en.uptodown.com/android"

[infinityforreddit]
#apkmirror-dlurl = "https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit/"
#uptodown-dlurl = "https://infinity-for-reddit.en.uptodown.com/android"
apkmirror-dpi = "120-640dpi"
# NOTE: apkmirror and uptodown sources cannot be used as they provide google play version (it crashes after patching), patreon version should be used, that's why I use archive.org
archive-dlurl = "https://archive.org/download/latest-infinity-patreon-for-revanced/apk"
# https://github.com/j-hc/revanced-magisk-module/issues/528
patcher-args = "-Oclient-id=WvoTj1mBciSr1k3Iuql-Hg"
# https://github.com/j-hc/revanced-magisk-module/issues/535
included-patches = "'Spoof client'"

[tumblr]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tumblr-inc/tumblr/"
uptodown-dlurl = "https://tumblr.en.uptodown.com/android"
apkmirror-dpi = "120-640dpi"
